version: '3'

services:
  olab-api:
    image: olab-api
    restart: always
    build: .
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ./OLab45-Api:/usr/src/app/Api
      - ./appsettings.json:/usr/src/app/Api/WebApiService/appsettings.json
      - ./OLab45-Common:/usr/src/app/Common
    env_file: .env
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.5.17-focal
    env_file: .env
    volumes:
      - ./data/db/mysql:/var/lib/mysql
      - ./data/scripts/:/docker-entrypoint-initdb.d/
